apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: mindbridge
  labels:
    app: content-service
spec:
  selector:
    app: content-service
  ports:
    - name: http
      port: 8007
      targetPort: 8007
  type: ClusterIP
