# Generated by Django 5.2.1 on 2026-05-25 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('booking', 'Booking Confirmation'), ('reminder', 'Session Reminder'), ('reaction', 'Community Reaction'), ('comment', 'Comment on Post'), ('mention', 'Mentioned in Post'), ('professional', 'Professional Update'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_new_message', models.BooleanField(default=True)),
                ('email_booking', models.BooleanField(default=True)),
                ('email_reminder', models.BooleanField(default=True)),
                ('email_community', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=True)),
                ('push_new_message', models.BooleanField(default=True)),
                ('push_booking', models.BooleanField(default=True)),
                ('push_reminder', models.BooleanField(default=True)),
                ('push_community', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
