# Generated by Django 5.2.1 on 2026-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('booking', 'Booking Confirmation'), ('booking_confirmed', 'Booking Confirmed'), ('reminder', 'Session Reminder'), ('reaction', 'Community Reaction'), ('comment', 'Comment on Post'), ('mention', 'Mentioned in Post'), ('professional', 'Professional Update'), ('follower', 'New Follower'), ('checkin', 'Daily Check-In Prompt'), ('ai_summary', 'AI Session Summary'), ('system', 'System Notification'), ('group_approved', 'Group Approved'), ('group_rejected', 'Group Rejected'), ('group_review_required', 'Group Requires Review')], max_length=30),
        ),
    ]
