# Generated by Django 5.2.1 on 2026-05-25 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('group_type', models.CharField(choices=[('anxiety', 'Anxiety Support'), ('grief', 'Grief & Loss'), ('depression', 'Depression'), ('ptsd', 'PTSD'), ('self_growth', 'Self-Growth'), ('stress', 'Stress Management'), ('relationships', 'Relationship Issues'), ('addiction', 'Addiction Recovery')], max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='group_covers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'community_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_moderator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group_memberships',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reaction_type', models.CharField(choices=[('heart', 'Heart (Love)'), ('hug', 'Hug (Support)'), ('fist', 'Fist (Strength)'), ('lightbulb', 'Lightbulb (Helpful)'), ('prayer', 'Prayer (Solidarity)'), ('sad', 'Sad Face (Empathy)')], max_length=15)),
            ],
            options={
                'db_table': 'reactions',
            },
        ),
    ]
