# Generated by Django 5.2.1 on 2026-05-26 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood_tag',
            field=models.CharField(blank=True, choices=[('anxious', 'Anxious'), ('sad', 'Sad'), ('angry', 'Angry'), ('overwhelmed', 'Overwhelmed'), ('hopeful', 'Hopeful'), ('grateful', 'Grateful'), ('calm', 'Calm'), ('happy', 'Happy')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('hate_speech', 'Hate Speech'), ('spam', 'Spam'), ('harmful', 'Harmful Content'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
