# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode_passwordresettoken_and_more'),
        ('community', '0003_post_mood_tag_report'),
    ]

    operations = [
        # Add new fields to CommunityGroup
        migrations.AddField(
            model_name='communitygroup',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_groups',
                to='users.user',
            ),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='is_user_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='approval_status',
            field=models.CharField(
                choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='approved',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_groups',
                to='users.user',
            ),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public - Anyone can join'), ('private', 'Private - Invite only')],
                default='public',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='custom_type',
            field=models.CharField(
                blank=True,
                help_text='Custom type for user-created groups',
                max_length=50,
            ),
        ),
        # Make group_type optional
        migrations.AlterField(
            model_name='communitygroup',
            name='group_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('anxiety', 'Anxiety Support'),
                    ('grief', 'Grief & Loss'),
                    ('depression', 'Depression'),
                    ('ptsd', 'PTSD'),
                    ('self_growth', 'Self-Growth'),
                    ('stress', 'Stress Management'),
                    ('relationships', 'Relationship Issues'),
                    ('addiction', 'Addiction Recovery'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        
        # Add expiration fields to Post
        migrations.AddField(
            model_name='post',
            name='is_saved',
            field=models.BooleanField(
                default=False,
                help_text='Saved messages won\'t be auto-deleted'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Messages auto-delete after 48 hours unless saved',
                null=True,
            ),
        ),
        
        # Add expiration fields to Comment
        migrations.AddField(
            model_name='comment',
            name='is_saved',
            field=models.BooleanField(
                default=False,
                help_text='Saved comments won\'t be auto-deleted'
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Comments auto-delete after 48 hours unless saved',
                null=True,
            ),
        ),
        
        # Create GroupInvitation model
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('invite_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expires after 7 days')),
                ('message', models.TextField(blank=True, help_text='Personal message for the invitee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='community.communitygroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='users.user')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='users.user')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitations', to='users.user')),
            ],
            options={
                'db_table': 'group_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
