# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode_passwordresettoken_and_more'),
        ('community', '0004_group_creation_and_expiration'),
    ]

    operations = [
        # Add AI review fields to CommunityGroup
        migrations.AddField(
            model_name='communitygroup',
            name='creation_reason',
            field=models.TextField(help_text='User\'s reason for creating this group'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='ai_questions',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated questions'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='ai_answers',
            field=models.JSONField(blank=True, default=dict, help_text='User answers to AI questions'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='ai_review_scores',
            field=models.JSONField(blank=True, default=list, help_text='Individual AI model scores'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='ai_total_score',
            field=models.IntegerField(blank=True, help_text='Combined AI score', null=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='ai_review_summary',
            field=models.TextField(blank=True, help_text='AI review summary'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='review_step',
            field=models.CharField(
                choices=[
                    ('reason', 'Reason Submitted'),
                    ('questions', 'Questions Generated'),
                    ('reviewing', 'AI Reviewing'),
                    ('complete', 'Review Complete')
                ],
                default='reason',
                max_length=20
            ),
        ),
    ]
