# Generated by Django 5.2.1 on 2026-06-06 03:09

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_ai_group_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitygroup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['is_approved', 'is_deleted'], name='group_approved_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='communitygroup',
            index=models.Index(fields=['approval_status'], name='group_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', 'is_deleted', 'created_at'], name='post_group_deleted_created_idx'),
        ),
    ]
