# Generated by Django 5.2.1 on 2026-06-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
