# Generated by Django 5.0.4 on 2026-06-06 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('email_new_message', models.BooleanField(default=True)),
                ('email_booking', models.BooleanField(default=True)),
                ('email_reminder', models.BooleanField(default=True)),
                ('email_community', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=True)),
                ('push_new_message', models.BooleanField(default=True)),
                ('push_booking', models.BooleanField(default=True)),
                ('push_reminder', models.BooleanField(default=True)),
                ('push_community', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('booking', 'Booking Confirmation'), ('booking_confirmed', 'Booking Confirmed'), ('reminder', 'Session Reminder'), ('reaction', 'Community Reaction'), ('comment', 'Comment on Post'), ('mention', 'Mentioned in Post'), ('professional', 'Professional Update'), ('professional_approved', 'Professional Approved'), ('professional_rejected', 'Professional Rejected'), ('follower', 'New Follower'), ('checkin', 'Daily Check-In Prompt'), ('ai_summary', 'AI Session Summary'), ('system', 'System Notification'), ('group_approved', 'Group Approved'), ('group_rejected', 'Group Rejected'), ('group_review_required', 'Group Requires Review')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
