# Generated by Django 5.0.4 on 2026-06-06 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('total_distress_indicators', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ai_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Thumbs Up'), (-1, 'Thumbs Down')], null=True)),
                ('detected_mood', models.CharField(blank=True, max_length=50)),
                ('mood_score', models.FloatField(blank=True, null=True)),
                ('distress_indicators', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aisession')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
