# Generated by Django 5.2.1 on 2026-05-28 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_professionalprofile_gender_favouriteprofessional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='payout_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notes', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='professionals.professionalprofile')),
            ],
            options={
                'db_table': 'session_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
